### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by timlinux** [nixta/null-island#2]
Hi! Could you add a license for the dataset you made? I'd like to use it in a project, but don't want to contravene your IP

Thanks!

**Comment by nixta** [comment]
Hmmm. There was no license on the source when I created this, but now there is. I guess I should just use that license (Creative Commons non-commercial). https://creativecommons.org/licenses/by-nc/4.0/legalcode

**Comment by nixta** [comment]
Hopefully [this](https://github.com/nixta/null-island#license) addresses your concerns. Let me know if not!
